name: fithub
description: "FitHub mobile project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.0
  bloc: ^8.1.4
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  auto_route: ^8.1.2
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.svg
    - assets/images/
